# Generated by Django 4.1.1 on 2022-09-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='imagen',
            field=models.ImageField(upload_to='servicios'),
        ),
    ]
