# Generated by Django 4.1.1 on 2022-10-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_articulos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='descuento',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='precio',
            field=models.FloatField(),
        ),
    ]
