# Generated by Django 4.1.1 on 2022-10-05 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_rename_pedido_id_lineapedido_pedido_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pedido',
            table='pedido',
        ),
    ]
