# Generated by Django 4.1.1 on 2022-10-05 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pedido',
            table='pedidos',
        ),
    ]
