# Generated by Django 4.1.1 on 2022-10-09 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_articulos_cantidad_alter_articulos_descuento_and_more'),
        ('pedidos', '0004_alter_pedido_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineapedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.articulos'),
        ),
    ]
