# Generated by Django 4.1.1 on 2022-10-09 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_lineapedido_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='active_account',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cui',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='email',
            field=models.EmailField(default='direccion@gmail.com', max_length=150),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fisrt_name',
            field=models.CharField(default='nombre', max_length=150),
        ),
        migrations.AddField(
            model_name='pedido',
            name='last_name',
            field=models.CharField(default='Apellidos', max_length=150),
        ),
        migrations.AddField(
            model_name='pedido',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='username',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=150),
        ),
    ]
