# Generated by Django 4.1.1 on 2022-10-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_pedido_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='operacion',
            field=models.CharField(default='compra', max_length=50),
        ),
    ]
