# Generated by Django 4.1.1 on 2022-10-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_alter_pedido_entregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
