# Generated by Django 4.1.1 on 2022-10-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_lineapedido_entregado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
