# Generated by Django 4.1.1 on 2022-10-09 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='cuenta_activa',
            new_name='active_account',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='intentos_login',
            new_name='login_attempts',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(default='direccion@gmail.com', max_length=150),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='fisrt_name',
            field=models.CharField(default='nombre', max_length=150),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='last_name',
            field=models.CharField(default='Apellidos', max_length=150),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='username',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=150),
        ),
    ]
