# Generated by Django 4.1.1 on 2022-10-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_cuenta_activa_usuarios_active_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cui',
            field=models.CharField(default='0', max_length=13),
        ),
    ]
