# Generated by Django 4.1.1 on 2022-10-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuarios_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='profile_image',
            field=models.ImageField(default='users_pictures/default.png', upload_to='users_pictures'),
        ),
    ]
