# Generated by Django 4.1.1 on 2022-10-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuarios_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='profile_image',
            field=models.FileField(default='users_pictures/default.png', upload_to='users_pictures'),
        ),
    ]
